###################
# Spring Profile ##
###################
server:
   port: 8090
###################
# Eureka Config  ##
###################
eureka:
   client:
      fetch-registry: true
      register-with-eureka: true
      service-url: 
         default-zone: http://localhost:8761/eureka
   instance:
      hostname: localhost
###################
# Gateway Config ##
###################
spring:
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
         routes:
          - id: user-service
            uri: lb://user-service  # lb = loadbalance
            predicates:
             - Path=/user/**        # ** es para acceder a cualquier ruta inferior
            filters:
             - RemoveRequestHeader=Cookie
          - id: car-service
            uri: lb://car-service  
            predicates:
             - Path=/car/**        
          - id: bike-service
            uri: lb://bike-service  
            predicates:
             - Path=/bike/**  

