apiVersion: {{ .Values.bikeService.apiVersion }}
kind: Service
metadata:
  name: {{ .Values.global.bikeService.service.name }}
  labels:
    app: {{ .Values.global.bikeService.name }}
spec:
  type: NodePort
  ports:
    - name: bike-service-port
      port: {{ .Values.bikeService.port }}
      targetPort: {{ .Values.bikeService.port }}
      nodePort: {{ .Values.bikeService.nodePort }}
  selector:
    app: {{ .Values.global.bikeService.name }}
