services:

  config-service:
    image: config-service:1.0.0
    ports:
      - 8888:8888
    environment:
      REPOSITORY_BRANCH: develop-servlet
      REPOSITORY_URL: https://github.com/pramosiz/spring-restful-app
      CONFIG_FILE_ROUTE: additional-resources/config-data

  eureka-service:
    image: eureka-service:1.0.0
    ports:
      - 8761:8761
    depends_on:
      - config-service
    environment:
      CONFIG_SERVER_URI: config-service
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER_URI: eureka-service

  rabbitmq:
    image: rabbitmq_user:v1
    ports:
      - 15672:15672
      - 5672:5672
  
  postgres:
    image: postgres:14.13 
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /Users/pabloramosizquierdo/Desktop/Pablo/Tecnologias/Dockers/PostgreSQL/data:/var/lib/postgresql/data

  user-service:
    image: user-service:1.0.0
    # Uncomment this for Swagger UI 
    # ports:
    #   - 8001:8001
    depends_on:
      - rabbitmq
      - postgres
      - eureka-service
    environment:
      PG_DB_URL: postgres
      PG_DB_PORT: 5432
      PG_DB_NAME: test
      PG_DB_USER: postgres
      PG_DB_PWD: postgres
      PG_DB_SCHEMA: user-app
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: test
      RABBITMQ_PWD: test
      RABBITMQ_VHOST: test
      CONFIG_SERVER_URI: config-service
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER_URI: eureka-service
      EUERKA_SERVER_PORT: 8761
  
  car-service:
    image: car-service:1.0.0
     # Uncomment this for Swagger UI 
    # ports:
    #   - 8002:8002
    depends_on:
      - rabbitmq
      - postgres
      - eureka-service
    environment:
      PG_DB_URL: postgres
      PG_DB_PORT: 5432
      PG_DB_NAME: test
      PG_DB_USER: postgres
      PG_DB_PWD: postgres
      PG_DB_SCHEMA: user-app
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: test
      RABBITMQ_PWD: test
      RABBITMQ_VHOST: test
      CONFIG_SERVER_URI: config-service
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER_URI: eureka-service
      EUERKA_SERVER_PORT: 8761
  
  bike-service:
    image: bike-service:1.0.0
     # Uncomment this for Swagger UI 
    # ports:
    #   - 8003:8003
    depends_on:
      - rabbitmq
      - postgres
      - eureka-service
    environment:
      PG_DB_URL: postgres
      PG_DB_PORT: 5432
      PG_DB_NAME: test
      PG_DB_USER: postgres
      PG_DB_PWD: postgres
      PG_DB_SCHEMA: user-app
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: test
      RABBITMQ_PWD: test
      RABBITMQ_VHOST: test
      CONFIG_SERVER_URI: config-service
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER_URI: eureka-service
      EUERKA_SERVER_PORT: 8761
  
  zipkin-server:
    image: bitnami/zipkin:3.4.4
    ports:
      - 9411:9411
