############################
#####  PostgreSQL Pod  #####
############################
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-pod
  labels:
    app: rabbitmq
spec:
  containers:
    - name: rabbitmq-user # Not allowed _ character
      image: rabbitmq_user:v1
      ports:
        - containerPort: 5672
        - containerPort: 15672
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      restartPolicy: Always
