gatewayService:
  apiVersion: v1
  replicas: 1
  minReadySeconds: 60
  image: gateway-service
  version: 1.0.0
  port: 8080
  nodePort: 30080
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"
