apiVersion: v1
replicas: 1
minReadySeconds: 5
image: user-service
version: 1.0.0
nodePort: 30001
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
