apiVersion: apps/{{ .Values.configService.apiVersion }}
kind: Deployment
metadata:
  name: {{ .Values.global.configService.deployment.name }}
  labels:
    app: {{ .Values.global.configService.name }}
spec:
  replicas: {{ .Values.configService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.configService.name }}
  strategy:
    type: RollingUpdate
  minReadySeconds: {{ .Values.configService.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.configService.name }}
    spec:
      containers:
        - name: {{ .Values.global.configService.name }}
          image: {{ .Values.configService.image }}:{{ .Values.configService.version }}
          ports:
            - containerPort: {{ .Values.global.configService.port }}
          env:
            - name: REPOSITORY_BRANCH
              value: {{ .Values.configService.repositoryBranch }}
            - name: REPOSITORY_URL
              value: {{ .Values.configService.repositoryUrl }}
            - name: CONFIG_FILE_ROUTE
              value: {{ .Values.configService.configFileRoute }}
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
          resources:
            requests:
              memory: {{ .Values.configService.resources.requests.memory }}
              cpu: {{ .Values.configService.resources.requests.cpu }}
            limits:
              memory: {{ .Values.configService.resources.limits.memory }}
              cpu: {{ .Values.configService.resources.limits.cpu }}


