carService:
  apiVersion: v1
  replicas: 1
  minReadySeconds: 60
  image: car-service
  version: 1.0.0
  port: 8002
  nodePort: 30002
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
