server:
  port: 8080
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_URI:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance-id:${random.name}}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ${USER_SERVICE_NAME:user-service}
          uri: lb://${USER_SERVICE_NAME:user-service}
          predicates:
            - Path=/api/v2/user/**
        - id: ${CAR_SERVICE_NAME:car-service}
          uri: lb://${CAR_SERVICE_NAME:car-service}
          predicates:
            - Path=/api/v2/car/**
        - id: ${BIKE_SERVICE_NAME:bike-service}
          uri: lb://${BIKE_SERVICE_NAME:bike-service}
          predicates:
            - Path=/api/v2/bike/**
