server:
  port: 8080
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_URI:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance-id:${random.name}}
    preferIpAddress: true
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: ${USER_SERVICE_NAME:user-service}
          uri: lb://${USER_SERVICE_URI:user-service}
          predicates:
            # - Path=/** # Replace this for use Swagger UI
            - Path=/api/v2/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: ${CAR_SERVICE_NAME:car-service}
          uri: lb://${CAR_SERVICE_URI:car-service}
          predicates:
            - Path=/api/v2/car/**
        - id: ${BIKE_SERVICE_NAME:bike-service}
          uri: lb://${BIKE_SERVICE_URI:bike-service}
          predicates:
            - Path=/api/v2/bike/**

  ###################################################################################################
  # Keycloak: GET http://localhost:8091/realms/UserServiceRealm/.well-known/openid-configuration   ##
  ###################################################################################################
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8091/realms/UserServiceRealm/protocol/openid-connect/auth
            user-info-uri: http://localhost:8091/realms/UserServiceRealm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8091/realms/UserServiceRealm/protocol/openid-connect/token
        registration:
          user-client: # Name of the Keycloak client
            provider: keycloak
            client-id: user-client
            client-secret: fVk4zIco4iwUWyGJkmaXsdDHqmWgoNlc
            authorization-grant-type: authorization_code
            #redirect-uri: http://localhost:8080/login/oauth2/code/user-client
            redirect-uri: "{baseUrl}/login/oauth2/code/user-client"
