apiVersion: {{ .Values.userService.apiVersion }}
kind: Service
metadata:
  name: {{ .Values.global.userService.service.name }}
  labels:
    app: {{ .Values.global.userService.name }}
spec:
  type: NodePort
  ports:
    - name: user-service-port
      port: {{ .Values.userService.port }}
      targetPort: {{ .Values.userService.port }}
      nodePort: {{ .Values.userService.nodePort }}
  selector:
    app: {{ .Values.global.userService.name }}
