apiVersion: {{ .Values.carService.apiVersion }}
kind: Service
metadata:
  name: {{ .Values.global.carService.service.name }}
  labels:
    app: {{ .Values.global.carService.name }}
spec:
  type: NodePort
  ports:
    - name: car-service-port
      port: {{ .Values.carService.port }}
      targetPort: {{ .Values.carService.port }}
      nodePort: {{ .Values.carService.nodePort }}
  selector:
    app: {{ .Values.global.carService.name }}
