apiVersion: v1
name: user-restful-app
description: A Helm chart for Kubernetes for user-restful-app
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: user-service
    version: 0.1.0
    # repository: "file://../user-service"
    tags:
      - user-service
  - name: bike-service
    version: 0.1.0
    # repository: "file://../bike-service"
    tags:
      - bike-service
  - name: car-service
    version: 0.1.0
    # repository: "file://../car-service"
    tags:
      - car-service
  - name: gateway-service
    version: 0.1.0
    # repository: "file://../gateway-service"
    tags:
      - gateway-service
  - name: postgres
    version: 0.1.0
    # repository: "file://../postgres"
    tags:
      - postgres
  - name: rabbitmq
    version: 0.1.0
    # repository: "file://../rabbitmq"
    tags:
      - rabbitmq
keywords:
  - user-restful-app
  - user-service
  - bike-service
  - car-service
  - gateway-service
  - gateway-server
  - gateway
  - postgres
  - postgresql
  - rabbit
  - rabbitmq

maintainers:
  - name: Pablo
    email: ramosizquierdop@gmail.com
