global:
  configService:
    name: config-service
    port: 8888
    deployment:
      name: config-service-deploy
    service:
      name: config-svc

  eurekaService:
    name: eureka-service
    port: 8761
    deployment:
      name: eureka-service-deploy
    service:
      name: eureka-svc

  userService:
    name: user-service
    deployment:
      name: user-service-deploy
    service:
      name: user-svc

  carService:
    name: car-service
    deployment:
      name: car-service-deploy
    service:
      name: car-svc

  bikeService:
    name: bike-service
    deployment:
      name: bike-service-deploy
    service:
      name: bike-svc

  postgresql:
    name: postgres
    port: 5432
    db: test
    user: postgres
    password: postgres
    schema: user-app
    deployment:
      name: postgres-deploy
    service:
      name: postgres-svc

  rabbitmq:
    name: rabbitmq
    amqpPort: 5672
    user: test
    password: test
    vhost: test
    deployment:
      name: rabbitmq-deploy
    service:
      name: rabbitmq-svc
