apiVersion: apps/{{ .Values.bikeService.apiVersion }}
kind: Deployment
metadata:
  name: {{ .Values.global.bikeService.deployment.name }}
  labels:
    app: {{ .Values.global.bikeService.name }}
spec:
  replicas: {{ .Values.bikeService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.bikeService.name }}
  strategy:
    type: RollingUpdate
  minReadySeconds: {{ .Values.bikeService.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.bikeService.name }}
    spec:
      containers:
        - name: {{ .Values.global.bikeService.name }}
          image: {{ .Values.bikeService.image }}:{{ .Values.bikeService.version }}
          ports:
            - containerPort: {{ .Values.bikeService.port }}
          env:
            - name: CONFIG_SERVER_URI
              value: {{ .Values.global.configService.service.name }}
            - name: CONFIG_SERVER_PORT
              value: "{{ .Values.global.configService.port }}"
            - name: PG_DB_URL
              value: {{ .Values.global.postgresql.service.name }}
            - name: PG_DB_PORT
              value: "{{ .Values.global.postgresql.port }}"
            - name: PG_DB_NAME
              value: {{ .Values.global.postgresql.db }}
            - name: PG_DB_USER
              value: {{ .Values.global.postgresql.user }}
            - name: PG_DB_PWD
              value: {{ .Values.global.postgresql.password }}
            - name: PG_DB_SCHEMA
              value: {{ .Values.global.postgresql.schema }}
            - name: RABBITMQ_HOST
              value: {{ .Values.global.rabbitmq.service.name }}
            - name: RABBITMQ_PORT
              value: "{{ .Values.global.rabbitmq.amqpPort }}"
            - name: RABBITMQ_USER
              value: {{ .Values.global.rabbitmq.user }}
            - name: RABBITMQ_PWD
              value: {{ .Values.global.rabbitmq.password }}
            - name: RABBITMQ_VHOST
              value: {{ .Values.global.rabbitmq.vhost }}
            - name: EUREKA_SERVER_URI
              value: {{ .Values.global.eurekaService.service.name }}
            - name: EUREKA_SERVER_PORT
              value: "{{ .Values.global.eurekaService.port }}"
          resources:
            requests:
              memory: {{ .Values.bikeService.resources.requests.memory }}
              cpu: {{ .Values.bikeService.resources.requests.cpu }}
            limits:
              memory: {{ .Values.bikeService.resources.limits.memory }}
              cpu: {{ .Values.bikeService.resources.limits.cpu }}
