server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: ${REPOSITORY_BRANCH:develop-servlet}
          uri: ${REPOSITORY_URL:https://github.com/pramosiz/spring-restful-app}
          search-paths: ${CONFIG_FILE_ROUTE:additional-resources/config-data}
          
  application:
    name: @project.name@
    version: @project.version@
    description: @project.description@