################
# Spring Data ##
################
server:
  port: 8081
application:
  version: @project.version@
  description: Application to define files configuration to Microservices
  java: @java.version@
  maven: @maven.version@
  encoding: @project.build.sourceEncoding@

spring:
  application:
    name: config-service
   
##########
# Cloud ##
########## 
  cloud:
    config:
      server:
        git:
          default-label: config-server      # Branch
          uri: https://github.com/pramosiz/spring-restful-app
          search-paths: config-data         # Folder
          
  
