server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server      # Branch
          uri: https://github.com/pramosiz/spring-restful-app
          search-paths: config-data         # Folder
          
  application:
    name: config-service
